name: Compilar Executavel Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONUTF8: 1 # Resolve o erro de símbolos/Unicode na compilação

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Configurar Motor Visual (Flutter)
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Instalar Bibliotecas
      run: |
        pip install -r requirements.txt
        
    - name: Construir o Programa (.exe)
      # flet build cria um executável 100% independente e profissional
      run: |
        flet build windows
        
    - name: Disponibilizar para Download
      uses: actions/upload-artifact@v4
      with:
        name: Holerite_DHL_Windows
        path: build/windows/

